services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - ./.env.local
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  worker:
    build:
      context: .
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./.env.local
    networks:
      - app-network

networks:
  app-network:
